services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      db-service:
        condition: service_healthy
    environment:
      DB_HOST: db-service 
      DB_PORT: 5432
      DB_NAME: logistics_db
      DB_USER: postgres
      DB_PASSWORD: YourPassword123
      SERVER_PORT: 8000

  db-service: 
    image: postgres:15
    container_name: logistics-db-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourPassword123
      POSTGRES_DB: logistics_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/Init.sql:/docker-entrypoint-initdb.d/Init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d logistics_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data: